Added echo_server code
pinglinh/echo_server pull request #1
Opened 2016-11-13 20:04 UTC by pinglinh

Please add comments on how to improve this code.

2016-11-13 20:07 UTC, pinglinh commented on echo_server.rb
> +	end
testing

2016-11-14 10:07 UTC, cnak commented on echo_server.rb
> +	def initialize(welcome, instructions)
Unused input parameters. - "welcome" and "instructions"

2016-11-14 10:08 UTC, cnak commented on echo_server.rb
> +
Think about your public facing interface.

Perhaps the below methods could be private?

2016-11-14 10:09 UTC, cnak commented on echo_server.rb
> +
Not sure about this method.  :/

2016-11-14 10:10 UTC, cnak commented on echo_server.rb
> +
Not sure why @@user_input is a class variable

2016-11-14 10:12 UTC, cnak commented on echo_server.rb
> +
Perhaps it'll be easier to read if you group related methods together.

welcome_message
instruction_message
goodbye_message

2016-11-14 10:13 UTC, cnak commented on echo_server.rb
> +
exit entered reads a bit awkwardly.

"while exit is not false do ....."  I personally prefer "while exit is true do this"

2016-11-14 10:14 UTC, cnak commented on echo_server.rb
> +
Good small start method

2016-11-14 10:44 UTC, cnak requested changes
Please look at the comments above.

2016-11-19 09:51 UTC, pinglinh commented on echo_server.rb
> +	def initialize(welcome, instructions)
Hmm not sure how I would have it printed first when the server starts?

2016-11-27 01:19 UTC, merged